### ISSUE TITLE
Enemy bodies despawn too fast

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#101]
Npcs despawn after maybe 3 seconds, had to wait for a quest npc to respawn because my inventory was full, but they despawned before I could delete an item and loot the mob

**Comment by Kebful** [comment]
*AOHGM* 
 Related to the respawn rate being too quick

**Comment by Aoh1578** [comment]
Duplicate
https://github.com/Duskhaven-Reforged/bug-reports/issues/70
