### ISSUE TITLE
NPC Combat Reset Pathing

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#130]
Creator: Proprvilin 
Shadowglen NPCs have a chance to randomly path past you during combat, then stop out of range and act as though they are rooted (regardless of whether you follow them or not).

Mangy Nightstalkers have been the most frequently affected thus far (haven't left Shadowglen yet), with 4 out of 32 having done this after being auto-attacked. The first just walked ~20 yards and then reset - now resuming its un-aggro'd patrol from the new position; the second moved ~8 yards and then came back; the third went in a half circle (as if it could not reach my location, such as if I had jumped atop an object - I hadn't) around me, then reached a point from which it resumed ordinary combat pathing; the fourth moved two steps and then acted rooted, regardless of where I stood.

**Comment by Aoh1578** [comment]
Duplicate 
https://github.com/Duskhaven-Reforged/bug-reports/issues/179
https://github.com/Duskhaven-Reforged/bug-reports/issues/196
https://github.com/Duskhaven-Reforged/bug-reports/issues/109
