### ISSUE TITLE
Dungeon's Respawn Locations

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#156]
Creator: Aoh 
The following dungeon’s respawn locations are ‘empty’ and spawn into nowhereland

My suggested (xyz) next to each for a good respawn location, manually checked with go xyz

SFK (-233 1566 78)
Wailing Caverns (-731 -2218 20)
BFD (4247 744 -21)
Deadmines (-11208 1671 26)
Scarlet Monastery (2883 -811 162)
Gnomeregan (-5163 923 261)
Razorfen Kraul (-4468 -1674 85)
Razorfen Downs (-4657 -2519 87)
Uldaman (-6071 -2955 213)
Zul'Farrak (-6801 -2893 9)
Maraudon (1419 2908 137)
Temple of Atal'Hakkar (-10450 -3825 150)
Blackrock Depths (-7179 -921 170)
Blackrock Spire (-7493 -1128 267)
Scholomance (1266 -2561 99)
Stratholme (3352 -3379 147)
Dire Maul (-3523 1122 162)

**Comment by Aoh1578** [comment]
Hater implemented a solution for this issue -- Aoh
