### ISSUE TITLE
Gryphons at flight master bugged

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#176]
Creator: Epicly 
Looks weird
 ![image](https://gyazo.com/774d31b9e2097dbe489dd41b98b04b85)

**Comment by Kebful** [comment]
*Aoh* 
 Example in Tanaris: https://i.imgur.com/9xnvoMo.png

Felwood: https://i.imgur.com/qqplA9Y.png

**Comment by Aoh1578** [comment]
Duplicate 
https://github.com/Duskhaven-Reforged/bug-reports/issues/73
