### ISSUE TITLE
Scarlet Defender SM Armory resets

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#179]
Creator: Epicly 
Scarlet defenders in SM Armory resets once they get below 15-20%ish health

**Comment by Kebful** [comment]
*Epicly* 
 Mobs inside crusaders chapel does the same, inside SM cath

**Comment by Kebful** [comment]
*Aoh* 
 Related to flee, note this is happening for most (all?) mobs that runs away

**Comment by Aoh1578** [comment]
Duplicate issue -- Aoh
https://github.com/Duskhaven-Reforged/bug-reports/issues/153
https://github.com/Duskhaven-Reforged/bug-reports/issues/130
