### ISSUE TITLE
elder plainstrider

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#188]
Creator: UnknownSun 
Unable to loot elder plainstriders animation happens no loot pops up

**Comment by Kebful** [comment]
*Aoh* 
 This creature sometimes drops no loot which is intended, however issue is the respawn time.

I was able to kill and loot it but had to loot it immediately.

**Comment by Aoh1578** [comment]
No problem with this specific mob, just the known issue of quick respawn time -- Aoh
