### ISSUE TITLE
Enemies without pathing will reset health if they try to run

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#196]
Creator: Dylbert 
Enemies that try to run away but cant due to pathing will instead heal between auto attacks. Video here for clarification. https://youtu.be/8rYWB3dGyqk

**Comment by Aoh1578** [comment]
Duplicate issue -- Aoh
https://github.com/Duskhaven-Reforged/bug-reports/issues/179
https://github.com/Duskhaven-Reforged/bug-reports/issues/153
https://github.com/Duskhaven-Reforged/bug-reports/issues/130
