### ISSUE TITLE
Searing Whelp getting a lot of resists

### ISSUE THREAD

**Issue by Kebful** [Duskhaven-Reforged/bug-reports#245]
Creator: Breaker 
Searing Whelps in Dustwallow Marsh is weirdly resisting around 1 of every 5 spells i cast on them. All of them have been nature spells (Lightning bolt, earth shock, and Wind Sear)

**Comment by Aoh1578** [comment]
Aoh
This npc has a "129" resistance to nature spells, normal to be resisting them
